export default {
    headline:{
      fontSize:24,
      fontFamily:'System',
      fontWeight:'400',
    },
    title:{
      fontSize:20,
      fontFamily:'System',
      fontWeight:'500',
    },
    titleBold:{
      fontSize:22,
      fontFamily:'System',
      fontWeight:'bold',
    },
    subheading18:{
      fontSize:18,
      fontFamily:'System',
      fontWeight:'400',
    },
    subheading18b:{
      fontSize:20,
      fontFamily:'System',
      fontWeight:'bold',
    },
    button:{
      fontSize:15,
      fontFamily:'System',
      fontWeight:'400',
    },
    subheadingBold:{
      fontSize:16,
      fontFamily:'System',
      fontWeight:'bold',
    },
    subheading:{
      fontSize:16,
      fontFamily:'System',
      fontWeight:'400',
    },
    bodyBold:{
      fontSize:14,
      fontFamily:'System',
      fontWeight:'bold',
    },
    body:{
      fontSize:14,
      fontFamily:'System',
      fontWeight:'400',
    },
    bodyItalic:{
      fontSize:14,
      fontFamily:'System',
      fontWeight:'400',
      fontStyle:'italic'
    },
    captionBold:{
      fontSize:12,
      fontFamily:'System',
      fontWeight:'bold',
    },
    caption:{
      fontSize:12,
      fontFamily:'System',
      fontWeight:'400',
    },
    captionItalic:{
      fontSize:12,
      fontFamily:'System',
      fontWeight:'400',
      fontStyle:'italic'
    }
  }